sudo: false
language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

matrix:
  fast_finish: true

install:
  - composer self-update

before_script:
  - composer install --no-interaction --no-scripts

script:
  - ./vendor/bin/phpunit --coverage-clover=coverage.clover

after_script:
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
notifications:
  slack:
    rooms:
      - stefanius:V64KfmqnpFtzsYuWfHI65Clg#travis